Repository prestojs/prestojs, pull requests merged in 2020-08, with the labels that each got.

#21 Feature/drf parsers and renderers
  django-testbed/django-root/django_site/settings/base.py
  django-testbed/frontend/src/models/User.js
  django-testbed/frontend/src/models/generated/BaseUser.js
  django-testbed/frontend/src/views/UserCreateUpdateView.js
  django-testbed/frontend/src/views/UserFilterForm.js
  django-testbed/frontend/src/views/UserListView.js
  python-packages/presto_drf/presto_drf/parsers.py
  python-packages/presto_drf/presto_drf/renderers.py
  python-packages/presto_drf/presto_drf/tests/test_parsers.py
  python-packages/presto_drf/presto_drf/tests/test_renderers.py
Labels: @prestojs/rest, priority, ready:for-review

#81 Feature/blank required
  django-testbed/frontend/src/models/User.js
  js-packages/@prestojs/final-form/src/FormItem.tsx
  js-packages/@prestojs/ui-antd/src/widgets/NullableBooleanWidget.tsx
  js-packages/@prestojs/viewmodel/src/fields/CharField.ts
  js-packages/@prestojs/viewmodel/src/fields/Field.ts
  js-packages/@prestojs/viewmodel/src/fields/NumberField.ts
  js-packages/@prestojs/viewmodel/src/fields/__tests__/Field.test.ts
  python-packages/presto_drf/setup.py
Labels: ready:for-review

#76 fix: remove FilterSet and FieldBinder
  django-testbed/frontend/src/models/User.js
  django-testbed/frontend/src/views/UserFilterForm.js
  django-testbed/frontend/src/views/UserListView.js
  js-packages/@prestojs/viewmodel/src/FieldBinder.ts
  js-packages/@prestojs/viewmodel/src/FilterSet.ts
  js-packages/@prestojs/viewmodel/src/fields/Field.ts
  js-packages/@prestojs/viewmodel/src/index.ts
Labels: priority, ready:for-review
